### ISSUE TITLE
Cannot use hostPath volume type

### ISSUE THREAD

**Issue by tomcsi** [ContainerSSH/ContainerSSH#209]
## Describe the bug

If I try to add volumes section to configmap I get this error message:
```
{"timestamp":"2021-05-19T20:30:24Z","level":"crit","code":"CORE_CONFIG_ERROR","message":"Invalid configuration in file /etc/containerssh/config.yaml (failed to read configuration file /etc/containerssh/config.yaml (yaml: unmarshal errors:\n  line 42: field hostPath not found in type v1.Volume))","details":{"module":"core"}}
```

## To Reproduce

1. Create configmap with this values:
```
apiVersion: v1
data:
  config.yaml: |
    log:
      level: "debug"
    backend: kubernetes
    security:
      shell:
        mode: disable
    kubernetes:
      connection:
        certFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        cacert: |
          <cacert>
      pod:
        consoleContainerNumber: 0
        metadata:
          namespace: tp-112520
        spec:
          volumes:
            - name: home
              hostPath:
                path: /home/ubuntu
                type: Directory
          containers:
            - name: shell
              image: containerssh/containerssh-guest-image
    ssh:
      hostkeys:
        - /etc/containerssh/host.key
    auth:
      url: http://<auth url>/
kind: ConfigMap
```
2. Restart containerssh pod

## Expected behavior

Run the containerssh pod, and if I connect to, that I can browse the directory that I mount from host.

## Version

containerssh/containerssh:0.4
