### ISSUE TITLE
ContainerSSH hangs when an IPv6 client connects

### ISSUE THREAD

**Issue by florath** [ContainerSSH/ContainerSSH#420]
## Describe the bug

I have two kubernetes clusters running: one with dual-stack (ipv4 + ipv6) enabled and one only with ipv4. containerssh is perfectly running on the ipv4-only setup but does not work on the dual-stack kubernetes.

## My environment

I run an auth-server on port 8080 as a separate container in the same pod on port 8080; same for config server on port 8081.

ipv4-only: kubernetes 1.23.3
dual-stack: kubernetes 1.23.2

Both containerssh instances installed using exactly the same helm chart.

## To Reproduce

Set up a dual-stack kubernetes and run containerssh using a dedicated auth- and config server.

## Expected behavior

containerssh also works on a dual-stack kubernetes.

## Version

If you can please insert the output of `containerssh --version` here:

```
$ containerssh --version

```

IMHO this is not really what you want :-)

```
$ /containerssh --version
flag provided but not defined: -version
Usage of /containerssh:
  -config string
    	Configuration file to load (has to end in .yaml, .yml, or .json)
  -dump-config
    	Dump configuration and exit
  -licenses
    	Print license information
```

Output from the kubectl describe:

```
    Image:          containerssh/containerssh:0.4.1
```

## Logs

It directly steps from 'SSH_CONNECTED' to 'SSH_AUTH_UNAVAILABLE':

```
{"timestamp":"2022-03-15T12:22:29Z","level":"debug","code":"SSH_CONNECTED","message":"Client connected","details":{"connectionId":"5c76a2a2323a49b380159d228986fd11","module":"ssh","remoteAddr":"x.x.x.x"}
{"timestamp":"2022-03-15T12:22:30Z","level":"info","code":"SSH_AUTH_UNAVAILABLE","message":"Keyboard-interactive authentication for user xxxxxx currently unavailable. ...
```

For me it looks that the containerssh process does not even try to reach the auth-server

A `netstat` shows, that in the ipv4-only setup there a some connections between the containerssh and the auth- and config server but none on the dual-stack installation:

```
/ $ netstat -nap 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::2222                 :::*                    LISTEN      1/containerssh
tcp        0      0 :::8080                 :::*                    LISTEN      -
tcp        0      0 :::8081                 :::*                    LISTEN      -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
```

Same on the ipv4-only (excerpt):

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:51456         127.0.0.1:8080          ESTABLISHED 1/containerssh
tcp        0      0 127.0.0.1:56048         127.0.0.1:8081          ESTABLISHED 1/containerssh
tcp        0      0 127.0.0.1:54642         127.0.0.1:8081          ESTABLISHED 1/containerssh
tcp        0      0 127.0.0.1:39988         127.0.0.1:8080          ESTABLISHED 1/containerssh
tcp        0      0 127.0.0.1:54320         127.0.0.1:8080          ESTABLISHED 1/containerssh
tcp        0      0 127.0.0.1:42782         127.0.0.1:8080          ESTABLISHED 1/containerssh
tcp        0      0 127.0.0.1:35856         127.0.0.1:8080          ESTABLISHED 1/containerssh
[...]
tcp        0      0 :::2222                 :::*                    LISTEN      1/containerssh
tcp        0      0 :::8080                 :::*                    LISTEN      -
tcp        0      0 :::8081                 :::*                    LISTEN      -
tcp        0      0 ::ffff:127.0.0.1:8081   ::ffff:127.0.0.1:54876  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8080   ::ffff:127.0.0.1:42776  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8080   ::ffff:127.0.0.1:46374  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8081   ::ffff:127.0.0.1:56066  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8080   ::ffff:127.0.0.1:50456  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8081   ::ffff:127.0.0.1:54346  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8080   ::ffff:127.0.0.1:42754  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8080   ::ffff:127.0.0.1:60450  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8081   ::ffff:127.0.0.1:56036  ESTABLISHED -
tcp        0      0 ::ffff:127.0.0.1:8080   ::ffff:127.0.0.1:60438  ESTABLISHED -
[...]
```

**Comment by janosdebugs** [comment]
Hello @florath thank you very much for this awesome and very detailed bug report. We have indeed not tested ContainerSSH with a dual stack setup, but we will now. I'll look into this and update this issue with my findings.

**Comment by janosdebugs** [comment]
Hey @florath thank you for your patience. I've managed to create a dual stack cluster (thanks to @bencurio for the environment), but ContainerSSH works as expected. However, there are a few things to be aware of with this deployment scenario:

1. Make sure that the service you create for both ContainerSSH and for the auth-config server have IPv6 enabled. Specifically, you will want to set `ipFamilyPolicy` to `PreferDualStack` or `RequireDualStack`.
2. Also make sure that your installed CNI actually supports dual stack operation and is configured to assign both IPv4 and IPv6 addresses. I used Calico, and needed to tune the Calico manifest before applying as [described here](https://projectcalico.docs.tigera.io/networking/ipv6#enable-dual-stack).
3. When debugging, please enable the [debug logging](https://containerssh.io/reference/logging/). Your ContainerSSH seems to not log everything, and debug logs help with setup problems.
4. You can get a shell inside the ContainerSSH pod using `kubectl exec -ti containerssh-pod-name /bin/sh`. You can use this to check if you can reach the auth-config server with telnet. The container is an Alpine Linux container, so you should be able to add packages for testing using `apk add`.

For reference, I'm adding my entire manifest, I hope this helps. If you have further questions or need help with your deployment please feel free to post them here, or [join the Slack channel](https://join.slack.com/t/containerssh/shared_invite/zt-w2ulatkm-hjGHk8OaxQCBX79XKJHAQQ). I'll close this issue for now, please feel free to reopen at any time.

```yaml
apiVersion: v1
items:
# Create a service account that ContainerSSH can use to create pods. This would need to point to a separate namespace in production.
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    name: containerssh
    namespace: default
  secrets:
  - name: containerssh-token-qb8p2
# Create a role ContainerSSH can use.
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: containerssh
    namespace: default
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/logs
    - pods/exec
    verbs:
    - '*'
# Bind the role to the service account
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: containerssh
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: containerssh
  subjects:
  - kind: ServiceAccount
    name: containerssh
    namespace: default
# Add the host key (private key) as a secret. See the ContainerSSH documentation on how to generate this for yourself.
- apiVersion: v1
  data:
    host.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdnJXTWNQaUkzTlZIelJDNzQzSEExRWdRa3dzcTBGVk5ZbVdwYWNhTnZCeEEvRzdqCnJjb29JMFU1RjJnQ1M2OE5KN1VQbzVkdW1MTnlFeGRJRlcvRjdxRi9IYUY3SUNicGE4MGNISitxanRSSXRWK3MKTVhVcEpBMERneGUxc0xMcnovZ3pFcjEwSFZ3RVFUTElWcS8yalJUVEdBYXBMT0FZRVVSWUduakliRGVOK2Uydgo4bkhjZ1A5N0JqWjdlL3VROW8vSUUrcDF0RGtjeEVKYWRxTHg0VDZ6UXcyRXVjcmxFcG4vRHZQUWFuMHRoajZxCi9LakMvUlFqVm0vRWxWdTdaZzdjamZYN2xQeGxPWVk4UkJXQVdxOEdIdFRNTTBkQXJJMmlQRFg0eWMrNENicy8KVFpiUzlzbXV1bmxkT2ZZS1VDdzVMWlo0NU11N3ExaWo4NE5iYndJREFRQUJBb0lCQUdKbVhGT0IrV1F3YS83RQpEcDRaZUl4UHJyV2dRblFDUDQ1d3RBd08xZHprbXlka3MvZGM0bjdvWGIvVSs3SS9YVU5LcWdvWHZZbnV0UUppCnRkL1JyMGdrYmVsRkE3bWdPanBVTjVnUlRqaXFFZVg3dW1ZK2RIN1VkQ1owMmx1VXhoV2xrL3lzWWpndjNVWWkKeExudHl3SWFaNXp5K3VGYnN5OWRtelAxZER4WlBKZ29tdXVTTzhoL201UXlrcHZ2V3FIZFZya081VDJ1NmJnbwpoaC9id2pKOWRLSGFBK3RqRkVVQnpmeXJlTW9tWmlkUjFzUFNPVzNEZkhlbUxUUDdkWU4rcWswVndkSFJ6Z2E3CnBKNm1qeTdremtDS2g5WkJiUVdJZVVHRHZhRTU1blhWUXBSVXZJMGdmZnU2ZkFqVmhVR05iNFlmZFI1cDZ4QzgKTi9rTVhaa0NnWUVBOVRoNUU3VU9DMU5GYzRTUnFwRE1mR2Y4aCsvcHI4THViS1A4M3hLUzZwRkFTTjZKQ21JKwpXMjRGUUxZM0JqTFB5amg4NUxJa0JkM0R6S3lzZ2xFZk5WSVBZRDZvbFpKcEVjN1RxRll3RUx1ZktaNU1hdUVjCmx5eUlIekc2VzhHelExSUNDUEhpZGFoWCtUdGZxN1dKd2pTM2NqU0xIT3dGRWZCWE1tRURKUFVDZ1lFQXh4ZWwKTkpiZG9CMlZTOUZGTVhobi85ZVVLWUpUL0s1am4xMDhVN1hmRjMwdGhOdHVnSTN0dTFBZmIrT01jTWYraXVDZQpnS0x6YVZxS0VBa3pVZSsrVTFrTVViMzk0S2cxUVRLbHRuVGk1ckE1ZjZGL0xkUEx6dExQVnBZaFdSWDBLdVFpCmdFMnNmOS8xWEdkb2pQYkh3NkR4Z291a1JxMDRtc1FhZFltSTRGTUNnWUJRT2Q2YXpQUkFUa2o5aHhTbENlUnMKbXhTcVlKcENqM0t6aGw4WG1Cc0t0T1NrTW5JQlBLMEwrbzJyWXpIVFRGSmc1V1F1NmYwUkVrR1p0N0JrbmllbwpxU1V3cHE4KzUveUovL0dOTkUxYlhCYXhaZ0c0UWRlNXVhNzdEYWpibGg2UTJzYWhxSWtmVnlrWStBelB2My9IClVybmxtajBkQkRhUWJPSUtNR1QzOVFLQmdHUjB2ZHNuTkhTUitMN2t2UEVWUEFTUGxpYkxwKzBiWVJFTVRtQSsKcUc2RnJ1NFdlazlMVGVUeHJLc2NPY1MrWk9WV0tTUG5GTUxYK0VuWEdwb0JTaHRzRnhjM3NsNGxBWm9BSURWTQpEU0V4VWhIZ1B2ZTBvbVdkWVJqamI3Z3ZwNS9zdEt2Z2hXV1FiNUZNYkNpVWJIOTlPZDhRN3JicXVHRC9DZ3E4CmR1QVpBb0dBWFVCZUM2ZzBTRkt1cSszbDlmSUQ4NU1aOUQ4NG1Rb1Nvb2owdXBCMWVIMU5ucVUzWlM3YzUyN3QKdGdUcGQ1ZHpEd3Q4NTRtR0lUSjRpUldkUkdUQm9tTVJWbk5TOTMvdkNhVDRkMk5KMUlwMmZYTEdlQVE5dHhocQpWT3JxUnJpVFFUNFhtdzVUeWN4bXp5L3ArbjdRbVhCUUMzSWVuTENmeFh5SHhPZ0x1YlU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
# Create a ContainerSSH config to use the service account in the pod itself.
- apiVersion: v1
  data:
    config.yaml: |
      ssh:
        hostkeys:
          - /etc/containerssh/host.key
      auth:
        url: http://authconfig:8080
      log:
        level: debug
      backend: kubernetes
      kubernetes:
        connection:
          host: kubernetes.default.svc
          cacertFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        pod:
          metadata:
            namespace: default
          spec:
            containers:
              - name: shell
                image: containerssh/containerssh-guest-image
  kind: ConfigMap
# Add a service for the authconfig server. Note the dualstack configuration.
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: authconfig
    name: authconfig
    namespace: default
  spec:
    ipFamilies:
    - IPv4
    - IPv6
    ipFamilyPolicy: PreferDualStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: authconfig
    type: ClusterIP
# Create a service for ContainerSSH. Again, note the dualstack configuration.
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: containerssh
    name: containerssh
    namespace: default
  spec:
    ipFamilies:
    - IPv4
    - IPv6
    ipFamilyPolicy: PreferDualStack
    ports:
    - port: 2222
      protocol: TCP
      targetPort: 2222
    selector:
      app: containerssh
    type: ClusterIP
# Create a deployment for the authconfig server. This server lets everyone in, don't use in production.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: authconfig
    name: authconfig
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: authconfig
    template:
      metadata:
        labels:
          app: authconfig
      spec:
        containers:
        - image: containerssh/containerssh-test-authconfig:0.4.1
          imagePullPolicy: IfNotPresent
          name: authconfig
          ports:
          - containerPort: 8080
            protocol: TCP
        restartPolicy: Always
# Deploy ContainerSSH with the service account and configmap applied.
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: containerssh
    name: containerssh
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: containerssh
    template:
      metadata:
        labels:
          app: containerssh
      spec:
        automountServiceAccountToken: true
        containers:
        - image: containerssh/containerssh:0.4
          imagePullPolicy: IfNotPresent
          name: containerssh
          ports:
          - containerPort: 2222
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/containerssh/host.key
            name: hostkey
            readOnly: true
            subPath: host.key
          - mountPath: /etc/containerssh/config.yaml
            name: config
            readOnly: true
            subPath: config.yaml
        restartPolicy: Always
        serviceAccount: containerssh
        serviceAccountName: containerssh
        volumes:
        - name: hostkey
          secret:
            secretName: containerssh-hostkey
        - configMap:
            name: containerssh-config
          name: config
```
