### ISSUE TITLE
SSH_AUTH_UNAVAILABLE occurs when OAuth2 authentication and Audit logging are enabled

### ISSUE THREAD

**Issue by dekimasoon** [ContainerSSH/ContainerSSH#586]
## Describe the bug

First of all thanks for the best project.

I was trying the OAuth2 authentication added in v0.5.
It works perfectly fine on its own and I was able to authenticate with AuthorizationCodeFlow.
However, when I enabled Audit logging in conjunction with it, I got `SSH_AUTH_UNAVAILABLE` and could not make SSH connections.

Then, I tried password authentication by Webhook, and I could confirm that it could be authenticated without any problem even if Audit logging was enabled, and an audit log was outputted.

The debug log of ContainerSSH at the time of the error is as follows.

```json
{"timestamp":"2024-01-31T14:20:06Z","level":"debug","code":"CORE_CONFIG_FILE","message":"Using configuration file /etc/containerssh/config.yaml...","details":{}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_POOL_STARTING","message":"Services are starting...","details":{"module":"service"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_STARTING","message":"SSH server is starting...","details":{"module":"service","service":"SSH server"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_STARTING","message":"Health check endpoint is starting...","details":{"module":"service","service":"Health check endpoint"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"HEALTH_AVAILABLE","message":"Health check endpoint available at http://0.0.0.0:7000","details":{"module":"health"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_RUNNING","message":"Health check endpoint is running.","details":{"module":"service","service":"Health check endpoint"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_RUNNING","message":"SSH server is running.","details":{"module":"service","service":"SSH server"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SSH_AVAILABLE","message":"SSH server running on 0.0.0.0:2222","details":{"module":"ssh"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_STARTING","message":"oAuth2 Redirect Server is starting...","details":{"module":"service","service":"oAuth2 Redirect Server"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"AUTH_OAUTH2_AVAILABLE","message":"oAuth2 redirect server is now available at http://0.0.0.0:8080","details":{"module":"auth"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_RUNNING","message":"oAuth2 Redirect Server is running.","details":{"module":"service","service":"oAuth2 Redirect Server"}}
{"timestamp":"2024-01-31T14:20:06Z","level":"info","code":"SERVICE_POOL_RUNNING","message":"All services are now running.","details":{"module":"service"}}
{"timestamp":"2024-01-31T14:20:34Z","level":"debug","code":"SSH_CONNECTED","message":"Client connected","details":{"connectionId":"aaf79a8cadf34a27b632fe6fb611d0fb","module":"ssh","remoteAddr":"10.0.46.163"}}
{"timestamp":"2024-01-31T14:20:34Z","level":"debug","code":"HTTP_CLIENT_REQUEST","message":"HTTP GET request to https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OHNsb0XVk/.well-known/openid-configuration","details":{"connectionID":"aaf79a8cadf34a27b632fe6fb611d0fb","endpoint":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OHNsb0XVk/","method":"GET","module":"auth","path":".well-known/openid-configuration","url":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/.well-known/openid-configuration","username":"test-user"}}
{"timestamp":"2024-01-31T14:20:34Z","level":"debug","code":"HTTP_CLIENT_RESPONSE","message":"HTTP response with status 200","details":{"connectionID":"aaf79a8cadf34a27b632fe6fb611d0fb","endpoint":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_OHNsb0XVk/","method":"GET","module":"auth","path":".well-known/openid-configuration","statusCode":200,"url":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/.well-known/openid-configuration","username":"test-user"}}
{"timestamp":"2024-01-31T14:20:54Z","level":"info","code":"SSH_AUTH_UNAVAILABLE","message":"Keyboard-interactive authentication for user test-user currently unavailable. (no answer for question)","details":{"connectionId":"aaf79a8cadf34a27b632fe6fb611d0fb","method":"keyboard-interactive","module":"ssh","reason":"no answer for question","remoteAddr":"10.0.46.163","username":"test-user"}}
{"timestamp":"2024-01-31T14:20:54Z","level":"debug","code":"HTTP_CLIENT_REQUEST","message":"HTTP GET request to https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/.well-known/openid-configuration","details":{"connectionID":"aaf79a8cadf34a27b632fe6fb611d0fb","endpoint":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/","method":"GET","module":"auth","path":".well-known/openid-configuration","url":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/.well-known/openid-configuration","username":"test-user"}}
{"timestamp":"2024-01-31T14:20:54Z","level":"debug","code":"HTTP_CLIENT_RESPONSE","message":"HTTP response with status 200","details":{"connectionID":"aaf79a8cadf34a27b632fe6fb611d0fb","endpoint":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/","method":"GET","module":"auth","path":".well-known/openid-configuration","statusCode":200,"url":"https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/.well-known/openid-configuration","username":"test-user"}}
```

My config.yaml is shown below.

```yaml
log:
  level: debug
ssh:
  hostkeys:
    - /etc/containerssh/host.key
auth:
  keyboardInteractive:
    method: oauth2
    oauth2:
      clientId: xxxxxxxxxxxxxxxxxxxxxxxxxx
      clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      provider: oidc
      oidc:
        url: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_XXXXXXXXX/
        authorizationCodeFlow: true
        redirectURI: https://xxx.com/
audit:
  enable: true
  format: binary
  storage: file
  intercept:
    stdin: true
    stdout: true
    stderr: true
    passwords: true
  file:
    directory: /var/log/audit
backend: kubernetes
kubernetes:
  connection:
    host: kubernetes.default.svc
    cacertFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  pod:
    metadata:
      namespace: containerssh-guests
    spec:
      containers:
        - name: shell
          image: containerssh/containerssh-guest-image
```

## To Reproduce

Enabling OAuth2 authentication with AuthorizationCodeFlow and Audit Logging at the same time.
I have not tested whether this occurs with DeviceFlow.

## Expected behavior

Can be authenticated using OAuth2 and audit logs are output.

## Version

v0.5.0
