### ISSUE TITLE
SFTP configuration example

### ISSUE THREAD

**Issue by ironreality** [ContainerSSH/ContainerSSH#589]
## What would you like to add/change in the documentation?

I'd like to upload files to the guest pods using SFTP.
While the documentation hints it's possible I can't find any related finite snippet or example both on containerssh.io and github.
Please suggest how to configure SFTP properly.

**Comment by mweissdigchg** [comment]
+1

**Comment by tsipinakis** [comment]
Hi, enabling sftp is done through the `subsystem` section in the backend, It is indeed hidden under `Other options` with no example in the documentation.

There used to be a full example in the [dockerrun backend](https://containerssh.io/v0.5/deprecations/dockerrun/?h=subsyste#changing-the-configuration-structure)

It's a good idea to add documentation about subsystems as it's not obvious.

```yaml
    # Subsystems that can be requested.
    subsystems:
      sftp: /usr/lib/openssh/sftp-server
```

**Comment by mweissdigchg** [comment]
Thanks to @tsipinakis last post I was able to set this up for kubernetes.
For all who have found their way here the example for kubernetes would be:
```yaml
kubernetes:
  connection:
    subsystems:
      sftp: /usr/lib/openssh/sftp-server
```
