### ISSUE TITLE
openid-connect with keycloak - "Failed to decode HTTP response"

### ISSUE THREAD

**Issue by Zappelphilipp** [ContainerSSH/ContainerSSH#601]
the documentation is unfortunately a bit poor in this regard, but i have already tried a few settings and obviously fail at the very end.

I basically followed these howtos:
* https://docs.nginx.com/nginx/deployment-guides/single-sign-on/keycloak/
* https://stackoverflow.com/questions/39792385/keycloak-openid-connect-userinfo
* https://keycloak.discourse.group/t/keycloak-missing-data-in-the-userinfo-response/19550/3

when I log in via ssh, I immediately get a response:

```
Welcome to ContainerSSH! login with OAuth
admin
Please click the following link: http://10.11.51.78:8081/realms/master/device?user_code=SNXF-ARSS

Enter the following code: SNXF-ARSS
```

then I open the link and can click on “Release” and get the message that the login was successful. 

In the logs, however, I see ann:

```
{"timestamp":"2024-06-05T09:37:42Z","level":"debug","code":"HTTP_CLIENT_REQUEST","message":"HTTP GET request to http://10.11.51.78:8081/realms/master/protocol/openid-connect/userinfo","details":{"connectionID":"86444ce006644a34ab943184ec7d9859","endpoint":"http://10.11.51.78:8081/realms/master/","method":"GET","module":"auth","url":"http://10.11.51.78:8081/realms/master/protocol/openid-connect/userinfo","username":"admin"}}
{"timestamp":"2024-06-05T09:37:42Z","level":"debug","code":"HTTP_CLIENT_RESPONSE","message":"HTTP response with status 403","details":{"connectionID":"86444ce006644a34ab943184ec7d9859","endpoint":"http://10.11.51.78:8081/realms/master/","method":"GET","module":"auth","statusCode":403,"url":"http://10.11.51.78:8081/realms/master/protocol/openid-connect/userinfo","username":"admin"}}
{"timestamp":"2024-06-05T09:37:42Z","level":"debug","code":"HTTP_CLIENT_DECODE_FAILED","message":"Failed to decode HTTP response (EOF)","details":{"connectionID":"86444ce006644a34ab943184ec7d9859","endpoint":"http://10.11.51.78:8081/realms/master/","method":"GET","module":"auth","url":"http://10.11.51.78:8081/realms/master/protocol/openid-connect/userinfo","username":"admin"}}
{"timestamp":"2024-06-05T09:37:42Z","level":"debug","code":"HTTP_CLIENT_DECODE_FAILED","message":"Failed to decode HTTP response (EOF)","details":{"connectionID":"86444ce006644a34ab943184ec7d9859","endpoint":"http://10.11.51.78:8081/realms/master/","method":"GET","module":"auth","url":"http://10.11.51.78:8081/realms/master/protocol/openid-connect/userinfo","username":"admin"}}

```

my config.yaml
```
auth:
  keyboardInteractive:
    method: oauth2
    oauth2:
      clientId: "keycloak"
      clientSecret: "SECRET"
      provider: oidc
      oidc:
        url: http://10.11.51.78:8081/realms/master/
        deviceFlow: true
        authorizationCodeFlow: false
#        usernameField: "preferred_username"
#        authorizationFlow: false
```

what am i doing wrong?
