### ISSUE TITLE
Cannot create containerssh-agent in a specific docker network

### ISSUE THREAD

**Issue by Salim-berrima** [ContainerSSH/ContainerSSH#639]
## Describe the bug

the containerssh-agent as a docker backend is not taking the specific network that I provided but got created in the  default bridge network

## config.yaml file

```yaml
docker:
    connection:
        host: "unix:///var/run/docker.sock"
        cacert: ""
        cert: ""
        key: ""
    execution:
        container:
            hostname: ""
            domainname: ""
            user: ""
            attachstdin: false
            attachstdout: false
            networkingconfig:
              endpointsconfig:
                administrator_default: 
                  networkid: "9e8ecb7bab9a9c0e6cf957b42827c2df759246f89a33e5ef8815442880eabef1"
            attachstderr: false
            exposedports: {}
            tty: false
            openstdin: false
            stdinonce: false
            env: []
            cmd: []
            healthcheck: null
            argsescaped: false
            image: custom-agent/containerssh-agent:v0
            volumes: {}
            workingdir: ""
            entrypoint: []
            networkdisabled: false
            macaddress: ""
            onbuild: []
            labels:
                creator: containerssh
            stopsignal: ""
            stoptimeout: null
            shell: []
        platform: null
        containername: ""
        auth: null
        mode: session
        network: 
          name: "administrator_default"          
        shellCommand:
            - /bin/bash
        disableAgent: false
        subsystems:
            sftp: /usr/lib/openssh/sftp-server
        imagePullPolicy: IfNotPresent
        exposeAuthMetadataAsEnv: false
```
It should be created in the administrator_default network not in the bridge network

## docker inspect 'containerssh-agent' 

```json 
           "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null,
                    "NetworkID": "daf1f55dbf4ad5902ea4661f31cb0987e0f842641cc8cd3fae3082cb012c6ac1",
                    "EndpointID": "bf9236a882cde711afe3968e203bfac5c55ec85f12b457d74cbdc9f2e8321130",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": null
                }
            }
```

## ContainerSSH version: Latest

Can you fix this or can you provide me how to hardcode the docker network for the containerssh-agent
