### ISSUE TITLE
Connect users to existing persistent container

### ISSUE THREAD

**Issue by tsipinakis** [ContainerSSH/ContainerSSH#643]
## Please describe what you would like to see in ContainerSSH

In a described use-case users create their own pods on a kubernetes cluster through kubectl commands but would like to use SSH to access them remotely. It is requested to implement a feature where through the configuration server the SSH connection can be routed to a specific pod in a specific namespace (with the possibility to maybe create the pod if it doesn't exist).

## Please describe your use case

See above

Example configuration for this use-case. This can be hard-coded in the config for a static pod for all users, or dynamically provided through the config server.

```
backend: kubernetes
kubernetes:
  connection:
    <connection configuration here>
  pod:
     mode: persistent
     metadata:
         name: mypod
         namespace: mynamespace
     spec: (Optional, spec that will be used to create the pod if it doesn't exist.)
```
