### ISSUE TITLE
Better documentation would be nice.

### ISSUE THREAD

**Issue by mkfifos** [ContainerSSH/ContainerSSH#97]
## Please describe what you would like to see in ContainerSSH
First of all, this is a really cool and very intriguing project. That being said, I would love to see a much better documentation.

## Please describe the solution you'd like
Let me give you two examples.

Under https://github.com/ContainerSSH/ContainerSSH/blob/main/example/Dockerfile it says
```FROM containerssh/containerssh:0.3.1
# Added ONLY for permission reasons. Don't use in production.
USER 0
```
Could you elaborate? Why is it necessary to set USER to 0? What do you put in the Dockerfile in case of a production setup? If a service can run without privileges why don't you use USER to change to a non-root user?

Under https://github.com/ContainerSSH/auditlog/blob/main/README.md it says
```
This section will explain how to set up and use a logging pipeline. As a first step, you must create the logger. The easiest way to do that is to pass a config object.
```
Is the following part of the code? Code in which of the go sources? Isn't configuration usually done with the help of config files? Do I have to compile a new containerssh-testauthconfigserver each time I would like to change something in the configuration?

## Please describe your use case
I would like to test and deploy a containerssh-honeypot with asciinema logging enabled. Got the example running with the 0.4.0-PR3 versions of containerssh/containerssh and containerssh/containerssh-test-authconfig, but due to only superfical knowledge of the go-lang I'm having a hard time setting up a logging pipe.

**Comment by PhilippHomann** [comment]
As mentioned at the end of [this section](https://containerssh.io/getting-started/installation/#running-in-a-containerized-environment), the docker socket has to be writable by uid 1022 as this is the uid used inside the image.
I think to make the first run easier, the user is changed to root, as you won't have permission problems accessing the docker socket.

You are correct that configuration is done using config files.
As the readme states, its a developmer documentation for the auditlog package.
As mentioned in the [user documentation](https://containerssh.io/getting-started/configuration/) you can run `containerssh --dump-config` to get all configuration parameters.
Dump for auditlog configration:
```
audit:
    enable: false
    format: none
    storage: none
    file:
        directory: /var/log/audit
    s3:
        local: /var/lib/audit
        accessKey: ""
        secretKey: ""
        bucket: ""
        region: ""
        endpoint: ""
        cacert: ""
        acl: ""
        pathStyleAccess: false
        uploadPartSize: 5242880
        parallelUploads: 20
        metadata:
            ip: false
            username: false
    intercept:
        stdin: false
        stdout: false
        stderr: false
        passwords: false
```

You have to write your own authentication and configuration server.
You don't have to do this in golang.
You just have to implement the [API](https://containerssh.io/reference/api/authconfig/).
The containerssh-testauthconfigserver should just give a brief example.

To get your asciinema-honeypot running you have to adapt the configuration above like this:
```
audit:
    enable: true
    format: asciicinema
    storage: file
    file:
        directory: /data/asciicinema
```

Note: I'm not a developer of this project so not all my statements must be true...
